name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  # branches:
  #   include:
  #     - main
  paths:
    include:
      - 'cicd-2/platform/**'
      - 'infra-2/**'
            
pool:
  vmImage: 'ubuntu-latest'

resources:
- repo: self

parameters:
- name: environments
  type: object
  #default: ['dev' ,'prod']
  default: ['dev']
stages:
- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env }}_Environment
    displayName: Deploy ${{ env }} Environment
    jobs:
    - deployment: 'ApprovalCheck'
      environment: 'portal-infrastructure-${{ env }}'
    - job: Deploy_Infrastucture
      displayName: Deploy Infrastructure
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  
      variables:
        - template: variables/vars-deploy-${{ env }}.yaml
      steps:
     # tas for backend
      - template: steps/deploy-backend.yaml
        parameters:
          bicepFilePath: ${{ variables.bicepFilePath }}
          deploymentName: ${{ variables.deploymentName }}
          backendServiceArmConnection: ${{ variables.backendServiceArmConnection }}
          location: ${{ variables.location }}
          backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
      