name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  # branches:
  #   include:
  #     - main
  paths:
    include:
      - 'deploy/infrastructure/**'
      - 'cicd/platform/**'
      #temperory extra
      - 'deploy/**'

# pool: Linux Pool
pool: 
  vmImage: 'ubuntu-latest'
resources:
- repo: self
parameters:
- name: environments
  type: object
  # default: ['dev' ,'prod']
  default: ['dev']

stages:
- ${{ each env in parameters.environments }}:
  - stage: Deploy_${{ env }}_Environment
    displayName: Deploy ${{ env }} Environment
    jobs:
    - deployment: 'ApprovalCheck'
      environment: 'portal-infrastructure-${{ env }}'
    - job: Deploy_AKS
      displayName: Build AKS Cluster
      #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))  
      variables:
        - template: variables/vars-deploy-${{ env }}.yaml
      steps:
        - template: steps/deploy-aks.yaml
          parameters:
            environment: ${{ variables.environment }}
            location: ${{ variables.location }}
            resourceGroupName: ${{ variables.resource_group_name }}
            clusterName: ${{ variables.cluster_name }}
            kubernetesVersion: ${{ variables.kubernetes_version }}
            systemNodeCount: ${{ variables.system_node_count }}
            acrName: ${{ variables.acr_name }}
            workingDirectory: ${{ variables.workingDirectory }}
            backendType: ${{ variables.backendType }}
            backendServiceArmConnection: ${{ variables.backendServiceArmConnection }}
            backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
            backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
            backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
            backendAzureRmKey: ${{ variables.backendAzureRmKey }}

    # - job: Deploy_NGINX_Controller
    #   displayName: Deploy NGINX Controller
    #   #dependsOn: Deploy_AKS
    #   #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    #   variables:
    #     - template: variables/vars-deploy-${{ env }}.yaml
    #   steps:
    #     - template: steps/deploy-nginx-controller.yaml
    #       parameters:
    #         environment: ${{ variables.environment }}
    #         location: ${{ variables.location }}
    #         resourceGroupName: ${{ variables.resource_group_name }}
    #         clusterName: ${{ variables.cluster_name }}
    #         kubernetesVersion: ${{ variables.kubernetes_version }}
    #         systemNodeCount: ${{ variables.system_node_count }}
    #         acrName: ${{ variables.acr_name }}
    #         workingDirectory: ${{ variables.workingDirectory }}
    #         backendType: ${{ variables.backendType }}
    #         backendServiceArmConnection: ${{ variables.backendServiceArmConnection }}
    #         backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    #         backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    #         backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    #         backendAzureRmKey: ${{ variables.backendAzureRmKey }}

      #  Deploy_Cert_Manager
        # - template: steps/deploy-cert-manager.yaml

      # deploy temp extra
    # - job: Deploy_Temp_Extra
    #   displayName: Deploy Extra Services
    #   #dependsOn: Deploy_AKS
    #   #condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    #   variables:
    #     - template: variables/vars-deploy-${{ env }}.yaml
    #   steps:
    #     - template: steps/deploy-temp-extra.yaml
    #       parameters:
    #         environment: ${{ variables.environment }}
    #         location: ${{ variables.location }}
    #         resourceGroupName: ${{ variables.resource_group_name }}
    #         clusterName: ${{ variables.cluster_name }}
    #         kubernetesVersion: ${{ variables.kubernetes_version }}
    #         systemNodeCount: ${{ variables.system_node_count }}
    #         acrName: ${{ variables.acr_name }}
    #         workingDirectory: ${{ variables.workingDirectory }}
    #         backendType: ${{ variables.backendType }}
    #         backendServiceArmConnection: ${{ variables.backendServiceArmConnection }}
    #         backendAzureRmResourceGroupName: ${{ variables.backendAzureRmResourceGroupName }}
    #         backendAzureRmStorageAccountName: ${{ variables.backendAzureRmStorageAccountName }}
    #         backendAzureRmContainerName: ${{ variables.backendAzureRmContainerName }}
    #         backendAzureRmKey: ${{ variables.backendAzureRmKey }}

